### PR TITLE
Correct beta and R_eff calculations

### PR DESCRIPTION
**Pull request by pratikunterwegs**
This PR corrects epidemic dynamics:

1. Replaces $R_0$ in force of infection calculations with transmission parameter $\beta$;
2. Adds a new function `get_beta()` to calculate model $\beta$ for a country and infection (thanks @patcatgit);
3. Corrects the implementation of `r_eff()` to use model $\beta$;
4. Corrects `prepare_parameters.daedalus_country()` to provide appropriate contact matrix values;
5. Adds tests to check newly added functions.

There is a noticeable speed loss due to repeated calls to `base::eigen()` and `base::solve()` in `r_eff()`.

### CODE REVIEW

**Comment by pratikunterwegs** [comment]
Results for Australia-SARS 2004:

``` r
library(daedalus)
library(data.table)
library(ggplot2)

combinations = CJ(
  response_strategy = c(
    "none", "school_closures", "economic_closures", "elimination"),
  vaccine_investment = c("none", "low", "medium", "high"),
  sorted = FALSE
)

output_list = Map(
  combinations$response_strategy, combinations$vaccine_investment,
  f = function(x, y) {
    daedalus(
      "AUS", "sars_cov_1", response_strategy = x, vaccine_investment = y
    )
  }
)

costs_list = vapply(output_list, get_costs, "total", FUN.VALUE = 1)

combinations$cost = costs_list
combinations$response_strategy = factor(
  combinations$response_strategy,
  c("none", "school_closures", "economic_closures", "elimination")
)
combinations$vaccine_investment = factor(
  combinations$vaccine_investment,
  c("none", "low", "medium", "high")
)

ggplot(
  combinations, 
  aes(response_strategy, vaccine_investment, fill = cost)
) +
  geom_tile()+
  scale_fill_distiller(palette = "RdYlGn")
```



<sup>Created on 2024-10-29 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by richfitz** [comment]
I see time here increasing from 0.7s elapsed to 4.9 elapsed (10.8 user), which is pretty bad!  The profile is slightly odd though and I don't think that we can blame the r_eff calculation here entirely as that is only accounting for (in my profile) 13% total, with the solve being pretty cheap and the call to eigen being pretty expensive (9% total). These could be confused slightly by R using a multithreaded call to LAPACK/BLAS though.  

Consider the example case from the tests:

```r
time_end <- 700L
country_canada <- "Canada"
output <- daedalus(country_canada, "influenza_1918", time_end = time_end)
```
I popped in some diagnostics:

```diff
diff --git a/R/daedalus.R b/R/daedalus.R
index 50150fb..f4637fc 100644
--- a/R/daedalus.R
+++ b/R/daedalus.R
@@ -248,6 +248,7 @@ daedalus <- function(country,
     events = list(func = activation_event[["event_function"]], root = TRUE),
     ...
   )
+  n <- attr(data_stage_01, "istate")[[3]]
 
   # set switch parameter and log closure start time if not 0.0/FALSE
   rlang::env_poke(parameters[["mutables"]], "switch", TRUE)
@@ -298,6 +299,7 @@ daedalus <- function(country,
     events = list(func = termination_event[["event_function"]], root = TRUE),
     ...
   )
+  n <- c(n, attr(data_stage_02, "istate")[[3]])
 
   #### Stage 3 - vaccination start time to sim end time ####
   # carry over initial state
@@ -321,6 +323,8 @@ daedalus <- function(country,
     events = list(func = termination_event[["event_function"]], root = TRUE),
     ...
   )
+  n <- c(n, attr(data_stage_03, "istate")[[3]])
+  message(sprintf("Took %d steps (%s)", sum(n), paste(n, collapse = ", ")))
 
   # log simulation end time as closure end time if not already ended
   is_response_ended <- as.logical(
```

and in the old version I see 1729 steps and in the new version 18869 which explains most of the time difference when running, with most of that coming from the second phase:

```
old: Took 1729 steps (171, 607, 951)
new: Took 18869 steps (177, 17797, 895)
```

(EDIT: sorry - these are rhs evaluations, not steps!)

Can you investigate what is upsetting the second part so much?  The diagnostics `deSolve::diagnostics` from that phase are:

```
--------------------
lsodar return code
--------------------

  return code (idid) =  2 
  Integration was successful.

--------------------
INTEGER values
--------------------

  1 The return code : 2 
  2 The number of steps taken for the problem so far: 415 
  3 The number of function evaluations for the problem so far: 17797 
  5 The method order last used (successfully): 5 
  6 The order of the method to be attempted on the next step: 5 
  7 If return flag =-4,-5: the largest component in error vector 0 
  8 The length of the real work array actually required: 1762261 
  9 The length of the integer work array actually required: 1343 
 14 The number of Jacobian evaluations and LU decompositions so far: 13 
 15 The method indicator for the last succesful step,
           1=adams (nonstiff), 2= bdf (stiff): 2 
 16 The current method indicator to be attempted on the next step,
           1=adams (nonstiff), 2= bdf (stiff): 2 
 
--------------------
RSTATE values
--------------------

  1 The step size in t last used (successfully): 0.5727415 
  2 The step size to be attempted on the next step: 0.5727415 
  3 The current value of the independent variable which the solver has reached: 365 
  4 Tolerance scale factor > 1.0 computed when requesting too much accuracy: 0 
  5 The value of t at the time of the last method switch, if any: 131.4273 
 
--------------------
ROOT
--------------------

 NO root found 
```

changing atol/rtol here seems only to make things worse!  It looks like at time 131 we switch over to the stiff BDF method and we get *there* quite quickly - not sure if that will help diagnose things.

**Comment by pratikunterwegs** [comment]
Thanks, I can reproduce these results locally. Just looking at the output, there doesn't appear to be anything going on around t = 131 which would cause the shift to a stiff method. We don't have vaccination starting until t = 365 as well.

Rplot

**Comment by pratikunterwegs** [comment]
Largest `hmin` that works seems to be 1e-3, which gives the same results as here. Higher values (1e-2, 1e-1) cause solver failure.

**Comment by pratikunterwegs** [comment]
Interesting findings when setting the `response_time` to 300, so stage 2 spans 300:365 for vaccine investment = "none".

The speed isn't massively improved - from 3.3s to 2.8s, but the number of times RHS is called in stage 2 drops from 17,000 to 137.

Hard to say what might be going on here.

**Comment by pratikunterwegs** [comment]
Posting some benchmarking here. I've pushed a small contact matrix scaling change that seems to help with the Canada case and some others, but for some countries the model performance remains unchanged. I'm _very_ curious as to why this is. Potentially I need to be scaling the contact matrices better?

``` r
  library(daedalus)
  # okay for Canada
  microbenchmark::microbenchmark(
    f_none = {
      daedalus("CAN", "influenza_1918")
    },
    f_low = {
      daedalus("CAN", "influenza_1918", vaccine_investment = "low")
    },
    f_med = {
      daedalus("CAN", "influenza_1918", vaccine_investment = "medium")
    },
    f_high = {
      daedalus("CAN", "influenza_1918", vaccine_investment = "high")
    },
    times = 10
  )
#> Unit: milliseconds
#>    expr      min       lq     mean   median       uq      max neval
#>  f_none 595.1001 610.5547 660.4656 636.9841 704.4646 779.4638    10
#>   f_low 591.1032 595.2324 628.7772 610.7788 659.0165 725.3317    10
#>   f_med 594.8376 639.2914 705.5748 716.5725 765.3845 843.9460    10
#>  f_high 595.1797 606.2972 650.8520 644.4826 693.0845 718.0558    10

# okay for Norway
microbenchmark::microbenchmark(
  f_none = {
    daedalus("NOR", "influenza_1918")
  },
  f_low = {
    daedalus("NOR", "influenza_1918", vaccine_investment = "low")
  },
  f_med = {
    daedalus("NOR", "influenza_1918", vaccine_investment = "medium")
  },
  f_high = {
    daedalus("NOR", "influenza_1918", vaccine_investment = "high")
  },
  times = 10
)
#> Unit: milliseconds
#>    expr      min       lq     mean   median       uq      max neval
#>  f_none 626.7807 636.0009 680.6148 684.9610 693.7432 742.2727    10
#>   f_low 601.2133 634.4576 666.5086 660.3839 688.5762 749.6752    10
#>   f_med 631.7296 635.9530 670.5383 660.5173 684.0639 749.0945    10
#>  f_high 584.6130 601.0722 643.5177 621.2547 695.2074 735.3116    10

# partially okay for GB
microbenchmark::microbenchmark(
  f_none = {
    daedalus("GBR", "influenza_1918")
  },
  f_low = {
    daedalus("GBR", "influenza_1918", vaccine_investment = "low")
  },
  f_med = {
    daedalus("GBR", "influenza_1918", vaccine_investment = "medium")
  },
  f_high = {
    daedalus("GBR", "influenza_1918", vaccine_investment = "high")
  },
  times = 10
)
#> Unit: milliseconds
#>    expr       min        lq      mean    median        uq       max neval
#>  f_none 1953.8910 1971.8348 2015.2765 2012.1085 2057.2122 2091.7109    10
#>   f_low 2742.1953 2774.9530 2855.2109 2866.6554 2905.6108 2966.8188    10
#>   f_med  637.1100  655.4892  687.7756  676.0481  725.9898  754.0964    10
#>  f_high  621.8622  634.4557  677.6206  665.4235  731.5447  768.6106    10

# not okay for Thailand
microbenchmark::microbenchmark(
  f_none = {
    daedalus("THA", "influenza_1918")
  },
  f_low = {
    daedalus("THA", "influenza_1918", vaccine_investment = "low")
  },
  f_med = {
    daedalus("THA", "influenza_1918", vaccine_investment = "medium")
  },
  f_high = {
    daedalus("THA", "influenza_1918", vaccine_investment = "high")
  },
  times = 10
)
#> Unit: seconds
#>    expr      min       lq     mean   median       uq      max neval
#>  f_none 3.080526 3.145659 3.185536 3.195033 3.236325 3.258726    10
#>   f_low 3.630323 3.690799 3.745785 3.733147 3.794691 3.885052    10
#>   f_med 3.506472 3.539157 3.593643 3.590534 3.625743 3.714181    10
#>  f_high 3.390080 3.440156 3.493478 3.494266 3.552584 3.596209    10
```

<sup>Created on 2024-10-30 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by pratikunterwegs** [comment]
@richfitz could you take a look at this? I'm aiming to get this merged tomorrow so I can do a release on Friday latest after merging #46 as well.

It's got speed problems for sure, but I don't see a solution. Happy to try or implement options.

**Review by richfitz — APPROVED** [review]

**Comment by richfitz** [comment]
My apologies - let's get this merged and think about solutions after the workshop

**Pull request merged**
